// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4YbINA2BXdJeii-Geah7Ow6sKcLWvik',
    appId: '1:855707198315:web:597eda24423a867b08622e',
    messagingSenderId: '855707198315',
    projectId: 'ouvintecidadao',
    authDomain: 'ouvintecidadao.firebaseapp.com',
    storageBucket: 'ouvintecidadao.appspot.com',
    measurementId: 'G-GGLKSGW17Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB08cKIbOpERUsEcSLIEFwX1cgfotYMvco',
    appId: '1:855707198315:android:f79c8e94e59228ab08622e',
    messagingSenderId: '855707198315',
    projectId: 'ouvintecidadao',
    storageBucket: 'ouvintecidadao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdrYA-KoPnSITQgnWhuaLEgfaYghQ77B8',
    appId: '1:855707198315:ios:02dfc1c7a763548208622e',
    messagingSenderId: '855707198315',
    projectId: 'ouvintecidadao',
    storageBucket: 'ouvintecidadao.appspot.com',
    iosBundleId: 'com.example.ouvinteCidadao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdrYA-KoPnSITQgnWhuaLEgfaYghQ77B8',
    appId: '1:855707198315:ios:02dfc1c7a763548208622e',
    messagingSenderId: '855707198315',
    projectId: 'ouvintecidadao',
    storageBucket: 'ouvintecidadao.appspot.com',
    iosBundleId: 'com.example.ouvinteCidadao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv4YbINA2BXdJeii-Geah7Ow6sKcLWvik',
    appId: '1:855707198315:web:d1e4bf99c32f4dc908622e',
    messagingSenderId: '855707198315',
    projectId: 'ouvintecidadao',
    authDomain: 'ouvintecidadao.firebaseapp.com',
    storageBucket: 'ouvintecidadao.appspot.com',
    measurementId: 'G-BSGCYL8Q71',
  );
}
